### ISSUE TITLE
Typo in about

### ISSUE THREAD

**Issue by codehwang** [DogukanUrker/flaskBlog#9]
**Describe the bug**
Typo in  'About' section in the top right of this github page

**To Reproduce**

1. 'About' section in the top right of this github page
2. A typo in a message like below
Simple blog app.📜 Python + Flask + SQLite3 + WTFroms  + Passlib

**Expected behavior**
"WTFroms  " should be "WTForms" in an About message

**Screenshots**

**Desktop (please complete the following information):**

- OS: macOS 11.7.8
- Browser: chrome Version 115.0.5790.102 (Official Build) (x86_64)

**Smartphone (please complete the following information):**

**Additional context**

**Comment by DogukanUrker** [comment]
I can't believe I didn't notice this for so long. Fixed thank you 💜

**Comment by codehwang** [comment]
You are welcome. I configured my blog with flaskBlog. Thank you very much for developing nice codes.

**Comment by DogukanUrker** [comment]
Hello,I made major security updates to flaskBlog(Release v1.0.2 · DogukanUrker/flaskBlog (github.com))If you have a website using flaskBlog I strongly recommend to you update your site to flaskBlog v1.0.2v1.0.1Before CSRF Protection [flaskBlog v1.0.1]youtu.bev1.0.2After CSRF Protection [flaskBlog v1.0.2]youtu.beBest regards,Doğukan ÜrkerOn Jul 28, 2023, at 12:31 AM, code forever ***@***.***> wrote:You are welcome. I configured my blog with flaskBlog. Thank you very much for developing nice codes.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you modified the open/close state.Message ID: ***@***.***>
